// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "@popperjs/core"
import "bootstrap"
import "controllers/cursor"
import "controllers/banner"
import "controllers/loader"
import "controllers/mousemove_controller"
import "controllers/translation_controller"
import "controllers/form_controller"
import "controllers/wrapper"
import "controllers/boxes"
